services:
  gravity:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: gravity-iot
    ports:
      - "3030:3030"
    volumes:
      - gravity_config:/app/config.json
    restart: unless-stopped

volumes:
  gravity_config:
